--------------------------------------------------------
--  File created - Monday-June-05-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ABTEILUNG
--------------------------------------------------------

  CREATE TABLE "DEMO"."ABTEILUNG" 
   (	"ABTEILUNG_ID" NUMBER, 
	"ABTEILUNGSBEZEICHNUNG" VARCHAR2(50 BYTE), 
	"LEHRER_ID_ABTEILUNGSLEITER" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DEMO.ABTEILUNG
SET DEFINE OFF;
Insert into DEMO.ABTEILUNG (ABTEILUNG_ID,ABTEILUNGSBEZEICHNUNG,LEHRER_ID_ABTEILUNGSLEITER) values (1,'Wirtschaftsingenieurwesen','ZLA');
Insert into DEMO.ABTEILUNG (ABTEILUNG_ID,ABTEILUNGSBEZEICHNUNG,LEHRER_ID_ABTEILUNGSLEITER) values (2,'Informatik Abend','BF');
Insert into DEMO.ABTEILUNG (ABTEILUNG_ID,ABTEILUNGSBEZEICHNUNG,LEHRER_ID_ABTEILUNGSLEITER) values (3,'Inf.Fachschule/ Kolleg','BC');
Insert into DEMO.ABTEILUNG (ABTEILUNG_ID,ABTEILUNGSBEZEICHNUNG,LEHRER_ID_ABTEILUNGSLEITER) values (4,'Informatik Tag','SKO');
Insert into DEMO.ABTEILUNG (ABTEILUNG_ID,ABTEILUNGSBEZEICHNUNG,LEHRER_ID_ABTEILUNGSLEITER) values (5,'Kunst und Design','PRW');
--------------------------------------------------------
--  DDL for Index XPKABTEILUNG
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."XPKABTEILUNG" ON "DEMO"."ABTEILUNG" ("ABTEILUNG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ABTEILUNG
--------------------------------------------------------

  ALTER TABLE "DEMO"."ABTEILUNG" ADD CONSTRAINT "XPKABTEILUNG" PRIMARY KEY ("ABTEILUNG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DEMO"."ABTEILUNG" MODIFY ("ABTEILUNG_ID" NOT NULL ENABLE);
